sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      - cmake


script:
  - doxygen Doxyfile
  - cmake --build . -- -j2
  - ctest -j2
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: doc/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
