var namespacertl =
[
    [ "test", "namespacertl_1_1test.html", "namespacertl_1_1test" ],
    [ "ApproximationTlsLine2D", "classrtl_1_1_approximation_tls_line2_d.html", "classrtl_1_1_approximation_tls_line2_d" ],
    [ "ApproximationTlsLine3D", "classrtl_1_1_approximation_tls_line3_d.html", "classrtl_1_1_approximation_tls_line3_d" ],
    [ "ApproximationTlsPlane3D", "classrtl_1_1_approximation_tls_plane3_d.html", "classrtl_1_1_approximation_tls_plane3_d" ],
    [ "BoundingBoxND", "classrtl_1_1_bounding_box_n_d.html", "classrtl_1_1_bounding_box_n_d" ],
    [ "CAR_Segmenter", "classrtl_1_1_c_a_r___segmenter.html", "classrtl_1_1_c_a_r___segmenter" ],
    [ "Expansion", "structrtl_1_1_expansion.html", "structrtl_1_1_expansion" ],
    [ "Expansion< VariantResultType< VrsKnown... >, VariantResultType< VrsNew... >, T, Tfs... >", "structrtl_1_1_expansion_3_01_variant_result_type_3_01_vrs_known_8_8_8_01_4_00_01_variant_result_7425ba72fdf9c122875a3519fcbc8695.html", null ],
    [ "ExtractorChainFast", "classrtl_1_1_extractor_chain_fast.html", "classrtl_1_1_extractor_chain_fast" ],
    [ "ExtractorChainIncremental", "classrtl_1_1_extractor_chain_incremental.html", "classrtl_1_1_extractor_chain_incremental" ],
    [ "Frustum3D", "classrtl_1_1_frustum3_d.html", "classrtl_1_1_frustum3_d" ],
    [ "GeneralTf", "classrtl_1_1_general_tf.html", "classrtl_1_1_general_tf" ],
    [ "has_element_type", "structrtl_1_1has__element__type.html", "structrtl_1_1has__element__type" ],
    [ "has_identity", "structrtl_1_1has__identity.html", "structrtl_1_1has__identity" ],
    [ "has_metric", "structrtl_1_1has__metric.html", "structrtl_1_1has__metric" ],
    [ "has_nan", "structrtl_1_1has__nan.html", "structrtl_1_1has__nan" ],
    [ "has_random", "structrtl_1_1has__random.html", "structrtl_1_1has__random" ],
    [ "HasRandomImpl", "structrtl_1_1_has_random_impl.html", null ],
    [ "HasRandomImpl< Obj >", "structrtl_1_1_has_random_impl_3_01_obj_01_4.html", "structrtl_1_1_has_random_impl_3_01_obj_01_4" ],
    [ "HasRandomImpl< Obj, G, Gs... >", "structrtl_1_1_has_random_impl_3_01_obj_00_01_g_00_01_gs_8_8_8_01_4.html", "structrtl_1_1_has_random_impl_3_01_obj_00_01_g_00_01_gs_8_8_8_01_4" ],
    [ "IA_Segmenter", "classrtl_1_1_i_a___segmenter.html", "classrtl_1_1_i_a___segmenter" ],
    [ "is_dimensional", "structrtl_1_1is__dimensional.html", "structrtl_1_1is__dimensional" ],
    [ "is_invertible", "structrtl_1_1is__invertible.html", "structrtl_1_1is__invertible" ],
    [ "is_transformable", "structrtl_1_1is__transformable.html", "structrtl_1_1is__transformable" ],
    [ "is_transformable< Obj, GeneralTf< Tfs... > >", "structrtl_1_1is__transformable_3_01_obj_00_01_general_tf_3_01_tfs_8_8_8_01_4_01_4.html", "structrtl_1_1is__transformable_3_01_obj_00_01_general_tf_3_01_tfs_8_8_8_01_4_01_4" ],
    [ "is_variant_result", "structrtl_1_1is__variant__result.html", "structrtl_1_1is__variant__result" ],
    [ "is_variant_result< VariantResultType< Ts... > >", "structrtl_1_1is__variant__result_3_01_variant_result_type_3_01_ts_8_8_8_01_4_01_4.html", "structrtl_1_1is__variant__result_3_01_variant_result_type_3_01_ts_8_8_8_01_4_01_4" ],
    [ "LaTeXDoc", "classrtl_1_1_la_te_x_doc.html", "classrtl_1_1_la_te_x_doc" ],
    [ "LaTeXTable", "classrtl_1_1_la_te_x_table.html", "classrtl_1_1_la_te_x_table" ],
    [ "LaTeXTikz2D", "classrtl_1_1_la_te_x_tikz2_d.html", "classrtl_1_1_la_te_x_tikz2_d" ],
    [ "LaTeXTikz3D", "classrtl_1_1_la_te_x_tikz3_d.html", "classrtl_1_1_la_te_x_tikz3_d" ],
    [ "LineSegmentND", "classrtl_1_1_line_segment_n_d.html", "classrtl_1_1_line_segment_n_d" ],
    [ "LineSegmentND< 2, Element >", "classrtl_1_1_line_segment_n_d_3_012_00_01_element_01_4.html", "classrtl_1_1_line_segment_n_d_3_012_00_01_element_01_4" ],
    [ "LineSegmentND< 3, Element >", "classrtl_1_1_line_segment_n_d_3_013_00_01_element_01_4.html", "classrtl_1_1_line_segment_n_d_3_013_00_01_element_01_4" ],
    [ "LineSegmentND_common", "classrtl_1_1_line_segment_n_d__common.html", "classrtl_1_1_line_segment_n_d__common" ],
    [ "Matrix", "classrtl_1_1_matrix.html", "classrtl_1_1_matrix" ],
    [ "OptimizerContinuity2D", "classrtl_1_1_optimizer_continuity2_d.html", "classrtl_1_1_optimizer_continuity2_d" ],
    [ "OptimizerTotalError", "classrtl_1_1_optimizer_total_error.html", "classrtl_1_1_optimizer_total_error" ],
    [ "Polygon2D", "classrtl_1_1_polygon2_d.html", "classrtl_1_1_polygon2_d" ],
    [ "Polygon3D", "classrtl_1_1_polygon3_d.html", "classrtl_1_1_polygon3_d" ],
    [ "PostprocessorPolyline2D", "classrtl_1_1_postprocessor_polyline2_d.html", "classrtl_1_1_postprocessor_polyline2_d" ],
    [ "PostprocessorProjectEndpoints", "classrtl_1_1_postprocessor_project_endpoints.html", "classrtl_1_1_postprocessor_project_endpoints" ],
    [ "PrecArayBase", "structrtl_1_1_prec_aray_base.html", "structrtl_1_1_prec_aray_base" ],
    [ "PrecArray2D", "structrtl_1_1_prec_array2_d.html", "structrtl_1_1_prec_array2_d" ],
    [ "PrecArray3D", "structrtl_1_1_prec_array3_d.html", "structrtl_1_1_prec_array3_d" ],
    [ "PrecSums2D", "structrtl_1_1_prec_sums2_d.html", "structrtl_1_1_prec_sums2_d" ],
    [ "PrecSums2DNames", "structrtl_1_1_prec_sums2_d_names.html", "structrtl_1_1_prec_sums2_d_names" ],
    [ "PrecSums3D", "structrtl_1_1_prec_sums3_d.html", "structrtl_1_1_prec_sums3_d" ],
    [ "PrecSums3DNames", "structrtl_1_1_prec_sums3_d_names.html", "structrtl_1_1_prec_sums3_d_names" ],
    [ "PrecSumsBase", "structrtl_1_1_prec_sums_base.html", "structrtl_1_1_prec_sums_base" ],
    [ "Quaternion", "classrtl_1_1_quaternion.html", "classrtl_1_1_quaternion" ],
    [ "Recursion", "structrtl_1_1_recursion.html", "structrtl_1_1_recursion" ],
    [ "Recursion< VariantResultType< Vrs1... >, VariantResultType< Vrs2... >, Tfs... >", "structrtl_1_1_recursion_3_01_variant_result_type_3_01_vrs1_8_8_8_01_4_00_01_variant_result_type_93e43c20b3b848f32d4bdd5b4ee70240.html", null ],
    [ "RigidTfND", "classrtl_1_1_rigid_tf_n_d.html", "classrtl_1_1_rigid_tf_n_d" ],
    [ "RigidTfND< 2, Element >", "classrtl_1_1_rigid_tf_n_d_3_012_00_01_element_01_4.html", "classrtl_1_1_rigid_tf_n_d_3_012_00_01_element_01_4" ],
    [ "RigidTfND< 3, Element >", "classrtl_1_1_rigid_tf_n_d_3_013_00_01_element_01_4.html", "classrtl_1_1_rigid_tf_n_d_3_013_00_01_element_01_4" ],
    [ "RigidTfND_common", "classrtl_1_1_rigid_tf_n_d__common.html", "classrtl_1_1_rigid_tf_n_d__common" ],
    [ "RotationND", "classrtl_1_1_rotation_n_d.html", "classrtl_1_1_rotation_n_d" ],
    [ "RotationND< 2, Element >", "classrtl_1_1_rotation_n_d_3_012_00_01_element_01_4.html", "classrtl_1_1_rotation_n_d_3_012_00_01_element_01_4" ],
    [ "RotationND< 3, Element >", "classrtl_1_1_rotation_n_d_3_013_00_01_element_01_4.html", "classrtl_1_1_rotation_n_d_3_013_00_01_element_01_4" ],
    [ "RotationND_common", "classrtl_1_1_rotation_n_d__common.html", "classrtl_1_1_rotation_n_d__common" ],
    [ "StripIfUnique", "structrtl_1_1_strip_if_unique.html", "structrtl_1_1_strip_if_unique" ],
    [ "StripIfUnique< VariantResultType< T, Ts... > >", "structrtl_1_1_strip_if_unique_3_01_variant_result_type_3_01_t_00_01_ts_8_8_8_01_4_01_4.html", "structrtl_1_1_strip_if_unique_3_01_variant_result_type_3_01_t_00_01_ts_8_8_8_01_4_01_4" ],
    [ "TfChain", "classrtl_1_1_tf_chain.html", "classrtl_1_1_tf_chain" ],
    [ "TfTree", "classrtl_1_1_tf_tree.html", "classrtl_1_1_tf_tree" ],
    [ "TfTreeNode", "classrtl_1_1_tf_tree_node.html", "classrtl_1_1_tf_tree_node" ],
    [ "Transformation2D", "classrtl_1_1_transformation2_d.html", "classrtl_1_1_transformation2_d" ],
    [ "Transformation3D", "classrtl_1_1_transformation3_d.html", "classrtl_1_1_transformation3_d" ],
    [ "TranslationND", "classrtl_1_1_translation_n_d.html", "classrtl_1_1_translation_n_d" ],
    [ "TranslationND< 2, Element >", "classrtl_1_1_translation_n_d_3_012_00_01_element_01_4.html", "classrtl_1_1_translation_n_d_3_012_00_01_element_01_4" ],
    [ "TranslationND< 3, Element >", "classrtl_1_1_translation_n_d_3_013_00_01_element_01_4.html", "classrtl_1_1_translation_n_d_3_013_00_01_element_01_4" ],
    [ "TranslationND_common", "classrtl_1_1_translation_n_d__common.html", "classrtl_1_1_translation_n_d__common" ],
    [ "Unique", "structrtl_1_1_unique.html", "structrtl_1_1_unique" ],
    [ "Unique< VariantResultType< Us... >, T, Ts... >", "structrtl_1_1_unique_3_01_variant_result_type_3_01_us_8_8_8_01_4_00_01_t_00_01_ts_8_8_8_01_4.html", null ],
    [ "VariantResultRecursiveType", "structrtl_1_1_variant_result_recursive_type.html", "structrtl_1_1_variant_result_recursive_type" ],
    [ "VariantResultRecursiveType< Obj, GeneralTf< Tfs... > >", "structrtl_1_1_variant_result_recursive_type_3_01_obj_00_01_general_tf_3_01_tfs_8_8_8_01_4_01_4.html", "structrtl_1_1_variant_result_recursive_type_3_01_obj_00_01_general_tf_3_01_tfs_8_8_8_01_4_01_4" ],
    [ "VariantResultType", "classrtl_1_1_variant_result_type.html", "classrtl_1_1_variant_result_type" ],
    [ "VectorizerAFTLSPlaneProjections3D", "classrtl_1_1_vectorizer_a_f_t_l_s_plane_projections3_d.html", "classrtl_1_1_vectorizer_a_f_t_l_s_plane_projections3_d" ],
    [ "VectorizerAFTLSPolyline2D", "classrtl_1_1_vectorizer_a_f_t_l_s_polyline2_d.html", "classrtl_1_1_vectorizer_a_f_t_l_s_polyline2_d" ],
    [ "VectorizerAFTLSProjections3D", "classrtl_1_1_vectorizer_a_f_t_l_s_projections3_d.html", "classrtl_1_1_vectorizer_a_f_t_l_s_projections3_d" ],
    [ "VectorizerDouglasPeuckerND", "classrtl_1_1_vectorizer_douglas_peucker_n_d.html", "classrtl_1_1_vectorizer_douglas_peucker_n_d" ],
    [ "VectorizerFTLSPolyline2D", "classrtl_1_1_vectorizer_f_t_l_s_polyline2_d.html", "classrtl_1_1_vectorizer_f_t_l_s_polyline2_d" ],
    [ "VectorizerFTLSProjections3D", "classrtl_1_1_vectorizer_f_t_l_s_projections3_d.html", "classrtl_1_1_vectorizer_f_t_l_s_projections3_d" ],
    [ "VectorizerITLSProjections2D", "classrtl_1_1_vectorizer_i_t_l_s_projections2_d.html", "classrtl_1_1_vectorizer_i_t_l_s_projections2_d" ],
    [ "VectorizerITLSProjections3D", "classrtl_1_1_vectorizer_i_t_l_s_projections3_d.html", "classrtl_1_1_vectorizer_i_t_l_s_projections3_d" ],
    [ "VectorizerReumannWitkamND", "classrtl_1_1_vectorizer_reumann_witkam_n_d.html", "classrtl_1_1_vectorizer_reumann_witkam_n_d" ],
    [ "VectorND", "classrtl_1_1_vector_n_d.html", "classrtl_1_1_vector_n_d" ],
    [ "VectorND< 2, Element >", "classrtl_1_1_vector_n_d_3_012_00_01_element_01_4.html", "classrtl_1_1_vector_n_d_3_012_00_01_element_01_4" ],
    [ "VectorND< 3, Element >", "classrtl_1_1_vector_n_d_3_013_00_01_element_01_4.html", "classrtl_1_1_vector_n_d_3_013_00_01_element_01_4" ],
    [ "VectorND_common", "classrtl_1_1_vector_n_d__common.html", "classrtl_1_1_vector_n_d__common" ]
];