version: 2.1

jobs:
  build:
    docker:
      - image: "ubuntu:focal"

    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'

      - run:
          name: Installing GCC and BUILDING-ESSENTIAL
          command: 'apt-get update && apt-get install -y gcc g++ build-essential'

      - run:
          name: Installing TZDATA and CURL
          command: 'apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata curl'

      - run:
          name: Install CMAKE
          command: 'apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y cmake'

      - run:
          name: Install GTest
          command: './.circleci/install_gtest.sh'

      - run:
          name: Creating Build Files
          command: 'cmake . -DENABLE_TESTS=1 -DENABLE_EXAMPLES=1 && make'

      - run:
          name: Tests
          command: 'ctest .'
